export interface WorkerEnv extends Omit<
  CloudflareBindings,
  "DEPLOYMENT_ENVIRONMENT" | "MARKETING_ORIGIN" | "FUNCTIONAL_ORIGIN"
> {
  DEPLOYMENT_ENVIRONMENT: string;
  MARKETING_ORIGIN: string;
  FUNCTIONAL_ORIGIN: string;
  TURNSTILE_SECRET_KEY: string;
  TURNSTILE_SITE_KEY: string;
  ABUSE_IP_HMAC_KEY: string;
  ABUSE_IP_HMAC_PREVIOUS_KEY?: string;
  SECRET_PREPARATION_HMAC_KEY: string;
  SECRET_PREPARATION_HMAC_PREVIOUS_KEY?: string;
  PREPARATION_FLOOD_LIMITER: RateLimit;
}
